[mypy]
python_version = 3.10
ignore_missing_imports = True
follow_imports = silent
check_untyped_defs = True
no_implicit_optional = False
warn_unused_configs = True
exclude = (?x)(
    ^\.git/
    | ^\.pytest_cache/
    | ^__pycache__/
    | ^build/
    | ^dist/
  )
